var quoteList = [
    ["He who thinks little, errs much.", "Leonardo Da Vinci"],
    ["The pure and simple truth is rarely pure and never simple.","Oscar Wilde"],
    ["A man who does not think for himself does not think at all.","Oscar Wilde"],
    ["Your time is limited, so don’t waste it living someone else’s life.","Steve Jobs"],
    ["Don’t let the noise of others’ opinions drown out your own inner voice.","Steve Jobs"],
    ["Have the courage to follow your heart and intuition. They somehow already know what you truly want to become.","Steve Jobs"],
    ["The only way to do great work is to love what you do. If you haven’t found it yet, keep looking.","Steve Jobs"],
    ["When making a mistake, do not be afraid to correct it.","Confucius"],
    ["To study and not think is a waste. To think and not study is dangerous.","Confucius"],
    ["The journey of a thousand miles begins with a single step.","Lao Tze"],
    ["A good scientist has freed himself of concepts and keeps his mind open to what is.","Lao Tze"],
    ["Knowledge of the fact differs from knowledge of the reason for the fact.","Aristotle"],
    ["In all things of nature there is something of the marvelous.","Aristotle"],
    ["There is no failure except in no longer trying.","Elbert Hubbard"],
    ["The greatest mistake you can make in life is to be continually fearing you will make one.","Elbert Hubbard"],
    ["To avoid criticism, do nothing, say nothing, be nothing.", "Elbert Hubbard"],
    ["Everything that irritates us about others can lead us to an understanding of ourselves.","Carl Jung"],
    ["Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.","Isaac Newton"],
    ["Be less curious about people and more curious about ideas.","Marie Curie"],
    ["Nothing in life is to be feared, it is only to be understood.","Marie Curie"],
    ["The way of progress is neither swift nor easy.","Marie Curie"],
    ["Knowledge belongs to humanity, and is the torch which illuminates the world.","Louis Pasteur"],
    ["If you want to have good ideas you must have many ideas.", "Linus Pauling"],
    ["Never put your trust into anything but your own intellect.", "Linus Pauling"],
    ["Do unto others twenty-five percent better than you expect them to do unto you.", "Linus Pauling"],
    ["A happy man is too satisfied with the present to dwell too much on the future.","Albert Einstein"],
    ["Unthinking respect for authority is the greatest enemy of truth.","Albert Einstein"],
    ["The value of a college education is not the learning of many facts but the training of the mind to think.","Albert Einstein"],
    ["Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world.","Albert Einstein"],
    ["I have no special talents. I am only passionately curious.", "Albert Einstein"],
    ["The important thing is not to stop questioning.","Albert Einstein"],
    ["Everything is interesting if you go into it deeply enough.","Richard Feynman"],
    ["If it disagrees with experiment, it’s wrong. In that simple statement is the key to science.","Richard Feynman"],
    ["If at first you don’t succeed, that’s one data point.","Randall Munroe"],
    ["Do things without always knowing how they’ll turn out.","Randall Munroe"],
    ["Let me never fall into the vulgar mistake of dreaming that I am persecuted whenever I am contradicted.","Ralph Waldo Emerson"],
    ["We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.","T.S. Eliot"]
];