---
title: ChemBrains
timezone: America/New_York
collections:
  compound-classes:
    title: Compound Classes
    output: true
  functional-groups:
    title: Functional Groups
    output: true
  posts:
    title: Posts
    output: true
  reactions:
    title: Reactions
    output: true
  syntheses:
    title: Syntheses
    output: true
  uploads:
    title: Uploads
    output: true
name: ChemBrains
description: "created by chemistry students, for chemistry students"
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: jreel
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: http://jreel.github.io/chembrains
baseurl: /chembrains

permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
