---
title: ChemBrains
timezone: America/New_York

name: ChemBrains.com
description: "created by chemistry students, for chemistry students"
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  email:
  facebook: 
  github: jreel
  instagram: 
  linkedin: 
  rss:
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: http://jreel.github.io/chembrains
baseurl: /chembrains

permalink: "/:title/"
paginate: 5

collections:
  reactions:
    output: true


version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
