---
title: ChemBrains
timezone: America/New_York

name: ChemBrains
author: ChemBrains.com
description: "created by chemistry students, for chemistry students"
logo: http://jreel.github.io/chembrains/images/logo.png
footer-links:
  email: chembrains@outlook.com
  facebook: chembrains
  github: jreel
  instagram: 
  linkedin: chembrains
  rss: atom.xml
  twitter: chembrains
  stackoverflow: 
  youtube: chembrains
  googleplus: chembrains
disqus: 
google_analytics: 
url: http://jreel.github.io/chembrains
baseurl: /chembrains

permalink: "blog/:year/:month/:title/"
paginate: 5
paginate_path: "blog/page:num/"


collections:
  reactions:
    output: true
    permalink: "reactions/:path"
  reagents:
    output: true
    permalink: "reagents/:path"
  compound-classes:
    output: true
    permalink: "compound-classes/:path"
  functional-groups:
    output: true
    permalink: "functional-groups/:path"
  concepts:
    output: true
    permalink: "concepts/:path"



version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
